### ISSUE TITLE
Eject config?

### ISSUE THREAD

**Issue by egoist** [mozilla-neutrino/webpack-chain#25]
This is a **Feature Request**.

I wonder if you're interested in implementing the *eject* webpack config feature (similar to what `create-react-app` does):

```js
config.entry('client').add('src/index.js')

config.plugin('define')
  .use(webpack.DefinePlugin, [{foo: 'foo'}])
  .outputName('webpack.DefinePlugin')

config.toString() // or maybe config.toConfig({ string: true })
//=> '{"entry":{"client":["src/index.js"]},"plugins":[new webpack.DefinePlugin({\"foo\": \"foo\"})]}'
```

**Comment by eliperelman** [comment]
I think this is a reasonable feature. As a start, you could probably do something similar to what is happening in Neutrino when we call `--inspect`:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino/src/inspect.js

**Comment by edmorley** [comment]
Vue CLI have just implemented an even better version of inspect, in:
https://github.com/vuejs/vue-cli/commit/f6bfb632c8ed3ccd4c5c0e4f70b6e05041b3ce67

I think it seems reasonable to add `javascript-stringify` as a dependency of webpack-chain, and move this type of functionality into it, rather than making every consumer re-invent the wheel.

CC @yyx990803

**Comment by edmorley** [comment]
Fixed by #53, published in webpack-chain v4.7.0.
Many thanks to @yyx990803 for the PR!

**Comment by edmorley** [comment]
For anyone subscribed to this issue for use with Neutrino...

Neutruno v8.3.0 has just been released, which backports the upcoming Neutrino 9's improved `--inspect` feature, as `--inspect-new`.

**Comment by mindplay-dk** [comment]
Didn't work for me - here's a more general way:

https://github.com/neutrinojs/neutrino/issues/96#issuecomment-1164038570
